version: '3.7'

networks:
  Minio-Net:
    driver: bridge

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
#  image: quay.io/minio/minio:RELEASE.2022-07-08T00-05-23Z
  image: hub.litsoft.com.cn/tools/minio:RELEASE.2024-04-18T19-09-19Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: Admin
    MINIO_ROOT_PASSWORD: P@88W0rd
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3


# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  MinioCluster-1:
    <<: *minio-common
    container_name: MinioCluster-1
    restart: always
    user: root
    hostname: MinioCluster-1
    volumes:
      - ./Minio-Cluster/Minio-1/Data-1:/data1
      - ./Minio-Cluster/Minio-1/Data-2:/data2

  MinioCluster-2:
    <<: *minio-common
    container_name: MinioCluster-2
    restart: always
    user: root
    hostname: MinioCluster-2
    volumes:
      - ./Minio-Cluster/Minio-2/Data-1:/data1
      - ./Minio-Cluster/Minio-2/Data-2:/data2

  MinioCluster-3:
    <<: *minio-common
    container_name: MinioCluster-3
    restart: always
    user: root
    hostname: MinioCluster-3
    volumes:
      - ./Minio-Cluster/Minio-3/Data-1:/data1
      - ./Minio-Cluster/Minio-3/Data-2:/data2

  MinioCluster-4:
    <<: *minio-common
    container_name: MinioCluster-4
    restart: always
    user: root
    hostname: MinioCluster-4
    volumes:
      - ./Minio-Cluster/Minio-4/Data-1:/data1
      - ./Minio-Cluster/Minio-4/Data-2:/data2

  Minio-Nginx:
    image: hub.litsoft.com.cn/tools/nginx:1.24.0
    container_name: Minio-Nginx
    restart: always
    user: root
    hostname: Minio-Nginx
    volumes:
      - ./Nginx/Conf/minio-cluster-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - MinioCluster-1
      - MinioCluster-2
      - MinioCluster-3
      - MinioCluster-4


